#!/usr/bin/env node
/* Writes src/addons.generated.ts — the frontend half of an extension install.
 *
 * The backend takes its extensions from an environment variable at startup
 * (NOWSPACE_ADDONS). The frontend cannot: a Tauri build runs under
 * `script-src 'self'`, so an extension's register() has to be inside the
 * bundle. This is that step — run by `npm run build`, so a deployment
 * installs an extension by setting a variable rather than by editing a file
 * that `git reset --hard` would throw away on the next update.
 *
 *   NOWSPACE_ADDONS_UI="@nowspace/relay"        one published package
 *   NOWSPACE_ADDONS_UI="/opt/nowspace-relay"    a checkout, for a prototype
 *   NOWSPACE_ADDONS_UI="@nowspace/relay,@nowspace/other"
 *
 * Entries are import specifiers, passed through verbatim — the same string
 * npm was given to install it. Each package exports `register()`.
 *
 * Unset, it writes the empty stub, byte for byte what the repository holds.
 * That is deliberate: every build runs this, and a baseline build must leave
 * the working tree clean.
 */

import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "src", "addons.generated.ts");

const HEADER = `/* Generated by scripts/generate-addons.mjs — do not edit.
 *
 * The frontend half of backend/addons.py's list. Written at build time from
 * NOWSPACE_ADDONS_UI, because a Tauri build runs under \`script-src 'self'\`
 * and an extension's register() has to be inside the bundle: a runtime
 * \`import()\` from the backend origin would work in the browser and silently
 * not in the desktop app.
 *
 * Empty in the baseline, and empty is what ships. An extension is installed
 * by a deployment, never by a commit here — see docs/EXTENSIONS.md.
 */
`;

const EMPTY_BODY = `
export {};
`;

/** A specifier is a package name or a path; neither is a valid identifier. */
const aliasFor = (spec, i) =>
  "register_" + (spec.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "") || `addon${i}`);

const specs = (process.env.NOWSPACE_ADDONS_UI || "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean)
  .filter((s, i, all) => all.indexOf(s) === i);   // stable dedupe

let body;
if (specs.length === 0) {
  body = EMPTY_BODY;
} else {
  const imports = specs.map((s, i) => `import { register as ${aliasFor(s, i)} } from ${JSON.stringify(s)};`);
  const calls = specs.map((s, i) => `${aliasFor(s, i)}();`);
  body = `\n${imports.join("\n")}\n\n${calls.join("\n")}\n`;
}

const next = HEADER + body;

// Only write when it differs: an untouched mtime keeps Vite from treating a
// no-op build step as a change.
let current = null;
try {
  current = readFileSync(target, "utf8");
} catch {
  /* first run */
}
if (current !== next) {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, next, "utf8");
}

if (specs.length) {
  console.log(`addons.generated.ts: ${specs.join(", ")}`);
}
