/* Generated by scripts/generate-addons.mjs — do not edit.
 *
 * The frontend half of backend/addons.py's list. Written at build time from
 * NOWSPACE_ADDONS_UI, because a Tauri build runs under `script-src 'self'`
 * and an extension's register() has to be inside the bundle: a runtime
 * `import()` from the backend origin would work in the browser and silently
 * not in the desktop app.
 *
 * Empty in the baseline, and empty is what ships. An extension is installed
 * by a deployment, never by a commit here — see docs/EXTENSIONS.md.
 */

export {};
